### PR TITLE
Team Page modified as asked. Issue #18 . Added the team members. Added animation. There are cards , each card shows the team members, on hovering the cards flip and there the social media buttons are available. On hovering the buttons a simple animation is also added.

### PR DESCRIPTION
**Pull request by anjalisoni3655**
Pull Request Template

**Add an issue reference**

This is a reference to the issue #

**Description of the changes proposed in the PR**

The changes in the PR include

**Add relevant screenshots**

**Add mentions of person or team**

### CODE REVIEW

**Comment by smaranjitghose** [comment]
Please follow the structure of the page I mentioned in the issue: Eg for each contributor, there should be a different circular icon

**Comment by gauravdas014** [comment]
@smaranjitghose apart from the contributor is everything fine?

**Comment by anjalisoni3655** [comment]
@smaranjitghose apart from the contributor is everything fine?

**Comment by smaranjitghose** [comment]
Please read the description of the issue, I have specified everything there

**Comment by anushbhatia** [comment]
@anjalisoni3655 If want to include such kind of design use white cards for this add a soft gradient. If you need help just pm me with the colours.

If u want to just keep the design clean add a read more option and just keep a circular profile.

**Pull request closed without merging**
