### PR TITLE
issue #17   Created a blog page that has the same style similar to the webiste. Medium articls have been integrated. Added a header image in the blog page .

### PR DESCRIPTION
**Pull request by anjalisoni3655**
Pull Request Template

**Add an issue reference**

This is a reference to the issue #

**Description of the changes proposed in the PR**

The changes in the PR include

**Add relevant screenshots**

**Add mentions of person or team**

### CODE REVIEW

**Comment by smaranjitghose** [comment]
Please include a screenshot whenever you give PRs for the pages

**Comment by anjalisoni3655** [comment]
-




@smaranjitghose Check these once

**Comment by anjalisoni3655** [comment]
There was only one article in the link given by you, and I have integrated that.

**Comment by smaranjitghose** [comment]
Nice work

**Pull request merged**
